[package]
name = "zkboo-sha2"
version = "1.2.0"
edition = "2024"
description = "SHA-2 primitives for the ZKBoo ecosystem."
license = "LGPL-3.0-or-later"
documentation = "https://docs.rs/zkboo-sha2"
repository = "https://github.com/zkboo/zkboo-sha2"
keywords = ["zk", "zero-knowledge", "zkboo"]
categories = ["cryptography", "no-std"]

[dependencies]
zkboo = "1.0.0"

[dev-dependencies]
hex = "0.4.3"
blake3 = "1.8.3"
zkboo = { version = "1.2.0", features = ["parallel"] }
zeroize = { version = "1.8.2", default-features = false, features = [
    "zeroize_derive",
    "alloc",
] }


[features]
default = []
sha256 = ["zkboo/u32"]
sha512 = ["zkboo/u64"]
